// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package services

import (
	"sync"
)

// Injectors from dependency-injection.go:

// @ref: https://github.com/google/wire/issues/260#issuecomment-680134730
func dependencyInjection() *ServiceContainer {
	client := dBConn()
	iDbOperations := newDB(client)
	iShortener := newShortener(iDbOperations)
	serviceContainer := &ServiceContainer{
		DB:        iDbOperations,
		Shortener: iShortener,
	}
	return serviceContainer
}

// dependency-injection.go:

type ServiceContainer struct {
	DB        IDbOperations
	Shortener IShortener
}

var containerOnce sync.Once

var Container *ServiceContainer

func RegisterServiceContainer() *ServiceContainer {
	containerOnce.Do(func() {
		Container = dependencyInjection()
	})

	return Container
}
